spring.datasource.username=postgres
spring.datasource.password=******
spring.datasource.driverClassName=org.postgresql.Driver

flyway.baseline-on-migrate=true
server.port=3000

security.jwt.token.secret-key=secret
app.security.permit-all=/users/cards

spring.profiles.active=dev,monitoring

