#for docker
captcha.path=../../src/main/resources/static/pictures/captcha
spring.datasource.url=jdbc:postgresql://db:5432/portfolio

app.cors.allowed-origins=http://creator-sumy.pp.ua, https://creator-sumy.pp.ua, http://162.19.229.244

logging.level.root = info
logging.file.path=/log-back
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.total-size-cap=14MB